#!/bin/python


from pandas import read_csv
import pandas as pd



file1 = 'sample_data.csv'
file2 = 'sample_data2.csv'
file3 = 'sample_data3.csv'

elements_file1 = pd.read_csv( file1 )['name'].tolist()
elements_file2 = pd.read_csv( file2 )['name'].tolist()
elements_file3 = pd.read_csv( file3 )['name'].tolist()

# print (type(elements_file1))

tetha = list(set(elements_file1 + elements_file2 + elements_file3))
# print( tetha )

n_tetha = len(tetha)
F = [elements_file1, elements_file2, elements_file3]
list_file = [file1, file2, file3]

y = []

for i in range(len(tetha)):
    for j in range(len(F)):
        found = False
        for k in range(len(F[j])):
            if F[j][k] == tetha[i] :
                # y.append([list_file[j],tetha[i],1])
                mariette = [list_file[j], tetha[i], 1]
                # array = [ filename, element, bool ]
                y.append( mariette )
                found = True
                break

        if found == False :
            # y.append([list_file[j],tetha[i],0])
            y.append([list_file[j], tetha[i], 0])


list_of_file_from_y = []
for item in y:
    list_of_file_from_y.append( item[0] )

list_of_file_from_y = list(set(list_of_file_from_y))
print( "Element", end=' ')
for filename in list_of_file_from_y:
    print( filename, end=' ')

for(i=0; i<len(list_of_file_from_y); ++i ):
    print()
print()
# for item in y:
    # 0 = filename
    # 1 = element
    # 2 = boolean
